sudo: required
services:
  - docker

before_install:
  - docker build -t gleydsonjose/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gleydsonjose/react-test npm test

after_success:
  - docker build -t gleydsonjose/multi-client ./client
  - docker build -t gleydsonjose/multi-nginx ./nginx
  - docker build -t gleydsonjose/multi-server ./server
  - docker build -t gleydsonjose/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gleydsonjose/multi-client
  - docker push gleydsonjose/multi-nginx
  - docker push gleydsonjose/multi-server
  - docker push gleydsonjose/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-246155924995'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY